spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minikode?useUnicode=true&characterEncoding=utf-8
#    hikari:
#      jdbc-url: jdbc:mariadb://localhost:3306/minikode?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: '!biobio3730@'

server:
  port: 8081

#logging:
#  level:
#    root: debug